= Aufnahme Fragebogen HTL Leonding 
Melanie Bauer, Kathi Einzenberger, Mark Grünzweil und Henry Ladstätter 
1.0.0, {docdate},
ifndef::imagesdir[:imagesdir: images]
:sourcedir: ../src/main/java
:icons: font
:sectnums:    
:toc: left
:toclevels: 2 
:toc-title: Inhaltsverzeichnis 

== Pflichtenheft "Was mache ich"

=== Ausgangssituation
Die HTL Leonding ist eine HTL im oberösterreichischen Zentralraum mit ca. 1300 Schülern und den Fachabteilungen Medientechnik, Informatik, Medizintechnik und Elektrotechnik.

=== Istzustand
Seit 1997 gibt es an der HTL Leonding keine Aufnahmeverfahren mehr wie früher. Dazu gehörte eine Aufnahmeprüfung in Form eines Multiple-Choice-Tests. Schüler, die später an die Schule kamen, hatten dadurch keine Möglichkeit mehr, diesen Test zu machen.

=== Problemstellung
Schüler der HTL Leonding haben aktuell keine Möglichkeit, ihr Wissen zu testen und zu prüfen, ob sie die Aufnahmeprüfung bestanden hätten. Dadurch bekommen sie kein Feedback zu ihrem Wissensstand und können sich nicht gezielt auf die Anforderungen der Schule vorbereiten. Auch Schüler, die schon länger an der Schule sind, hätten so sehen können, ob sie die Prüfung geschafft hätten.

=== Zielsetzung
Es soll eine JavaFX-Anwendung entwickelt werden, mit der Schüler einen Aufnahmetest machen können. Die Anwendung soll den Schülern helfen, ihr Wissen zu testen und zu sehen, ob sie die Aufnahmeprüfung bestehen würden.

=== Anforderungen (Soll-Zustand)
Es soll eine JavaFX-Anwendung entwickelt werden, die Schülern einen Aufnahmetest ermöglicht. Die Anwendung soll folgende Funktionen bieten:

* Eine grafische Benutzeroberfläche, die Fragen und Antwortmöglichkeiten anzeigt.
* Die Möglichkeit, Antworten auszuwählen und zu ändern.
* Eine Auswertung der Antworten nach Testabschluss.
* Eine Rückmeldung zum Testergebnis und zu den richtigen Antworten.

Die Anwendung soll einfach zu bedienen und vollständig in JavaFX implementiert sein.

==== Funktionale Anforderungen
* Die Anwendung soll eine Benutzeroberfläche bieten, die es den Schülern ermöglicht, Fragen zu beantworten.
* Die Anwendung soll die Antworten der Schüler speichern und auswerten.
* Die Anwendung soll nach Abschluss des Tests eine Rückmeldung über das Testergebnis geben.
* Die Anwendung soll die richtigen Antworten anzeigen, damit die Schüler ihre Fehler nachvollziehen können.

==== Nicht-funktionale Anforderungen (NFA)
* Die Anwendung soll eine intuitive und benutzerfreundliche Oberfläche haben.
* Die Anwendung soll performant und ohne Verzögerungen arbeiten.
* Die Anwendung soll auf verschiedenen Betriebssystemen (Windows, macOS, Linux) lauffähig sein.
* Die Anwendung soll sicherstellen, dass die Daten der Schüler vertraulich behandelt werden.

=== Ziele
* Die Anwendung soll es den Schülern ermöglichen, ihr Wissen zu testen und zu überprüfen ob sie damals schon in die HTL gekommen wären.
* Die Anwendung soll es den Schülern ermöglichen, sich gezielt auf die Anforderungen der Schule vorzubereiten.


=== Mengengerüst

==== Datenbewegungen
   * Die Anwendung soll die Fragen und Antworten aus einer Datenbank laden. Die Bilder zu den Fragen sollen aus dem Dateisystem bei Bedarf geladen  werden können .

==== Datenbestände
   * Die Anwendung soll die Fragen und Antworten in einer Datenbank speichern. Die Bilder zu den Fragen sollen im Dateisystem gespeichert werden.

==== Anzahl gleichzeitiger Benutzer
   * Die Anwendung soll von mehreren Schülern gleichzeitig verwendet werden können.

=== Rahmenbedingungen

==== Technische Rahmenbedingungen
   * Die Anwendung soll in JavaFX implementiert werden.
   * Die Anwendung soll auf verschiedenen OS (Windows, macOS, Linux) ausführbar sein.
